/*
This file is automatically generated
seagull
C Source
*/

#include "seagull.h"

#include "Ft_Gpu.h"

Ft_Esd_BitmapInfo seagull__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 320,
	.Height = 240,
	.Format = COMPRESSED_RGBA_ASTC_4x4_KHR,
	.Stride = 1280,
	.Size = 76800,
	.File = "seagull.astc",
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Type = ESD_RESOURCE_FILE,
};

Ft_Esd_BitmapCell seagull(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &seagull__Info, 
		.Cell = cell 
	};
}


/* end of file */
